default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: detect-private-key
-   repo: local
    hooks:
    - id: version
      name: Check Python version
      entry: poetry run python --version
      language: system
      verbose: true
      pass_filenames: false
      always_run: true
    - id: black
      name: Format source code
      entry: poetry run python -m black
      args: ["--config", "pyproject.toml", "-q"]
      language: system
      require_serial: true
      types: [python]
    - id: isort
      name: Sort imports
      entry: poetry run python -m isort
      args: ["-sp", "setup.cfg", "-y"]
      language: system
      types: [python]
