[ttb]

# zone/platform details
model        = "SolarThermalTestbed"
cores        = []
frequencies  = []
schedule_tag = "ttb"

# experiment details
path_apps    = "bin"
path_data    = "data"

# connection details
driver_type  = "SSHUnixDriver"

[ttb.driver_params]
ip           = "82.130.102.133"
port         = 2322
user         = "rocketlogger"
group        = "rocketlogger"
key          = "$EXOT_ACCESS_DIR/solar.thermal.testbed_rsa"
# gateway      = "exot-gateway"
# HostName bb-1.ethz.ch

# zone mapping big Cluster
[big]
# zone/platform details
model        = "Sony Xperia Z5"
cores        = [4,5,6,7]
frequencies  = [384000, 480000, 633600, 768000, 864000, 960000, 1248000, 1344000, 1440000, 1536000, 1632000, 1728000, 1824000, 1958400]
schedule_tag = "Z5"

# experiment details
path_apps    = ""
path_data    = "/sdcard/exot/data"

# connection details
driver_type  = "ADBAndroidDriver"

[big.driver_params]
ip           = "172.31.43.130"
port         = 51808
user         = "exot"
group        = "exot"
key          = "$EXOT_ACCESS_DIR/exot.adb_key"
# gateway      = "exot-gateway"

# zone mapping LITTLE cluster
[LITTLE]
# zone/platform details
model        = "Sony Xperia Z5"
cores        = [0,1,2,3]
frequencies  = [384000, 460800, 600000, 672000, 768000, 864000, 960000, 1248000, 1344000, 1478400, 1555200]
schedule_tag = "Z5"

# experiment details
path_apps    = "bin/rel"
path_data    = "/sdcard/exot/data"

# connection details
driver_type  = "ADBAndroidDriver"

[LITTLE.driver_params]
ip           = "172.31.43.130"
port         = 51808
user         = "exot"
group        = "exot"
key          = "$EXOT_ACCESS_DIR/exot.adb_key"
# gateway      = "exot-gateway"

# zone mapping both cluster
[bigLITTLE]
# zone/platform details
model        = "Sony Xperia Z5"
cores        = [0,1,2,3,4,5,6,7]
frequencies  = []
schedule_tag = "Z5"

# experiment details
path_apps    = "bin/rel"
path_data    = "/sdcard/exot/data"

# connection details
driver_type  = "ADBAndroidDriver"

[bigLITTLE.driver_params]
ip           = "172.31.43.130"
port         = 51808
user         = "exot"
group        = "exot"
key          = "$EXOT_ACCESS_DIR/exot.adb_key"
# gateway      = "exot-gateway"

