# zone mapping big Cluster
[big]
# zone/platform details
model        = "Dragonboard 810"
cores        = [4,5,6,7]
frequencies  = [384000, 480000, 633600, 768000, 864000, 960000, 1248000, 1344000, 1440000, 1536000, 1632000, 1728000, 1824000, 1958400]
schedule_tag = "db810"

# experiment details
path_apps    = "bin"
path_data    = "data"

# connection details
driver_type  = "SSHUnixDriver"

[big.driver_params]
ip           = "172.31.43.139"
port         = 51808
user         = "exot"
group        = "exot"
key          = "$EXOT_ACCESS_DIR/id_ed25519"
# gateway      = "exot-gateway"

# zone mapping LITTLE cluster
[LITTLE]
# zone/platform details
model        = "Dragonboard 810"
cores        = [0,1,2,3]
frequencies  = [384000, 460800, 600000, 672000, 768000, 864000, 960000, 1248000, 1344000, 1478400, 1555200]
schedule_tag = "db810"

# experiment details
path_apps    = "bin"
path_data    = "data"

# connection details
driver_type  = "SSHUnixDriver"

[LITTLE.driver_params]
ip           = "172.31.43.139"
port         = 51808
user         = "exot"
group        = "exot"
key          = "$EXOT_ACCESS_DIR/id_ed25519"
# gateway      = "exot-gateway"

[bigLITTLE]
model        = "Dragonboard 810"
cores        = [0, 1, 2, 3, 4, 5, 6, 7]
frequencies  = []
schedule_tag = "db810"

# experiment details
path_apps    = "bin"
path_data    = "data"

# connection details
driver_type  = "SSHUnixDriver"

[bigLITTLE.driver_params]
ip           = "172.31.43.139"
port         = 51808
user         = "exot"
group        = "exot"
key          = "$EXOT_ACCESS_DIR/id_ed25519"
# gateway      = "exot-gateway"
