# Configuration name
name = "Test_Repetitouch"
# Save path
save_path = "./data"
# Optional: Local backup path
backup_path = "./data/_backup"
# Optional: Action to perform if experiment directory exists
experiment_exists_action = "overwrite" # overwrite, move, halt

# Optional: Backup configuration
# [BACKUP]
# user = ""
# host = ""
# ssh_key = ""
# port = ""
# path = ""

# Experiment settings
[EXPERIMENT]
type = "AppExecExperiment"
channel = "Thermal"

[EXPERIMENT.PHASES]

[EXPERIMENT.PHASES.test]
repetitions=4

[EXPERIMENT.PHASES.test.dropbox2]
schedules=[
           'configurations/examples/RepetiTouch/Sony_Xperia_Z5_Dropbox.rpt']
           'configurations/examples/RepetiTouch/Samsung_Galaxy_S5_SM-900H_Dropbox.rpt']
durations=[44.7,30.3]
environments=['Z5', 'S5']

[EXPERIMENT.PHASES.test.antutu3]
schedules=['configurations/examples/RepetiTouch/Sony_Xperia_Z5_AnTuTu.rpt'
           'configurations/examples/RepetiTouch/Samsung_Galaxy_S5_SM-900H_AnTuTu.rpt']
durations=[28.8,31.2]
environments=['Z5', 'S5']

# Experiment layers
[EXPERIMENT.LAYERS]
io = {name = "TimeValue", params = {timebase='ns'}, synchronise = false} 

# Experiment general settings
[EXPERIMENT.GENERAL]
sampling_period = 1e-3
delay_after_spawn = 0 #60.0
delay_after_auxiliary = 0 # 30.0
active_wait = true

# --------------------------------------------------------------------------
# Apps and zones
[ENVIRONMENTS.Bilbo.APPS]
src = {executable = "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver", zone = "bigLITTLE", type="standalone"}
snk = {executable = "ch.ethz.exot.thermalsc/.MeterService", zone = "bigLITTLE"}

# Platform settings -> source
[ENVIRONMENTS.Bilbo.src]
COMPONENT_NAME="ch.ethz.exot.intentproxy/.IntentProxyService"
ACTION="ch.ethz.exot.intents.IntentProxy.action.BUNDLE_EXTRAS"

[ENVIRONMENTS.Bilbo.src.ei]
"intent.flags"= 20
"looptimes"= 1
"replayspeed"= 1

[ENVIRONMENTS.Bilbo.src.es]
"intent.component"= "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver"
"intent.action"= "com.twofortyfouram.locale.intent.action.FIRE_SETTING"
"intent.extra.key"= "com.twofortyfouram.locale.intent.extra.BUNDLE"
"condition"= "None"
"action"= "Start Replay"

[ENVIRONMENTS.Bilbo.src.ez]
"appendingrecord"= false
"hidepanel"= true
"closeafteraction"= false
"silent"= false        

# Platform settings -> sink
[ENVIRONMENTS.Bilbo.snk]
# logging
logging.log_level = "info"

# host
host.log_header = true
host.start_immediately = false

# --------------------------------------------------------------------------
# Apps and zones
[ENVIRONMENTS.Frodo.APPS]
src = {executable = "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver", zone = "bigLITTLE", type="standalone"}
snk = {executable = "ch.ethz.exot.thermalsc/.MeterService", zone = "bigLITTLE"}

# Platform settings -> source
[ENVIRONMENTS.Frodo.src]
COMPONENT_NAME="ch.ethz.exot.intentproxy/.IntentProxyService"
ACTION="ch.ethz.exot.intents.IntentProxy.action.BUNDLE_EXTRAS"

[ENVIRONMENTS.Frodo.src.ei]
"intent.flags"= 20
"looptimes"= 1
"replayspeed"= 1

[ENVIRONMENTS.Frodo.src.es]
"intent.component"= "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver"
"intent.action"= "com.twofortyfouram.locale.intent.action.FIRE_SETTING"
"intent.extra.key"= "com.twofortyfouram.locale.intent.extra.BUNDLE"
"condition"= "None"
"action"= "Start Replay"

[ENVIRONMENTS.Frodo.src.ez]
"appendingrecord"= false
"hidepanel"= true
"closeafteraction"= false
"silent"= false        

# Platform settings -> sink
[ENVIRONMENTS.Frodo.snk]
# logging
logging.log_level = "info"

# host
host.log_header = true
host.start_immediately = false

