# Copyright (c) 2015-2020, Swiss Federal Institute of Technology (ETH Zurich)
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# ------------------------------------------------------------------------------------------------ #
#                                    General Experiment Parameters                                 #
# ------------------------------------------------------------------------------------------------ #
name = "Thermal-SC_DragonboardImitation"
save_path = "./data"
backup_path = "./data/_backup"
experiment_exists_action = "update" # Optional: Action to perform if experiment directory exists: overwrite, move, halt, update

[EXPERIMENT]
type = "AppExecExperiment"
channel = "ThermalSC"

[EXPERIMENT.LAYERS]
io  = {name = "TimeValue", params = {timebase='ns', synchronise = false}}
rdp = {name = "Normalise", params = {resampling_period_s=0.04, offset=22}}  # Resampling period and ambient temperature (offset)
lne = {name = "ThermalLabelRefactoring", params = {}}

[EXPERIMENT.GENERAL]
sampling_period = 1e-3
delay_after_spawn = 60.0
delay_after_auxiliary = 0.0
active_wait = true

# ------------------------------------------------------------------------------------------------ #
#                                     Experiment Phases                                            #
# ------------------------------------------------------------------------------------------------ #

[EXPERIMENT.PHASES]
[EXPERIMENT.PHASES.bm]
repetitions=10

[EXPERIMENT.PHASES.bm.androbench0]
schedules=[
 '../RepetiTouchFiles/S5/Benchmark/AndroBench/0_2019-07-16_09-33-00.rpt',
 '../RepetiTouchFiles/Z5/Benchmark/AndroBench/0_2019-07-21_13-43-00.rpt'
 ]
durations=[186.117580, 131.433588]
environments=['S5', 'Z5']
 
[EXPERIMENT.PHASES.bm.antutu0]
schedules=[
 '../RepetiTouchFiles/S5/Benchmark/AnTuTu/0_2019-08-08_17-45-00.rpt',
 '../RepetiTouchFiles/Z5/Benchmark/AnTuTu/0_2019-08-08_17-46-00_MitPause.rpt',
 ]
durations=[
            935.278840, 
           1014.240704, 
          ]
environments=['S5', 'Z5']

[EXPERIMENT.PHASES.bm.chrome2]
schedules=[
 '../RepetiTouchFiles/S5/Browsing/Chrome/2_2019-08-12_16-05-00.rpt',
 '../RepetiTouchFiles/Z5/Browsing/Chrome/2_2019-08-13_12-32-00_new.rpt'
 ]
durations=[275.663995, 205.046]
environments=['S5', 'Z5']

[EXPERIMENT.PHASES.bm.angrybirdsrio1]
schedules=[
 '../RepetiTouchFiles/S5/Game/AngryBirdsRio/1_2019-08-08_20-10-00_new.rpt',
 '../RepetiTouchFiles/Z5/Game/AngryBirdsRio/1_2019-08-13_22-23-00.rpt_new'
 ]
durations=[
           158.942426, 
           151.324664
          ]
environments=['S5', 'Z5']
 
[EXPERIMENT.PHASES.bm.youtube0]
schedules=[
 '../RepetiTouchFiles/S5/Video/YouTube/0_2019-08-12_20-29-00.rpt',
 '../RepetiTouchFiles/Z5/Video/YouTube/0_2019-08-13_15-24-00.rpt'
 ]
durations=[208.866472, 166.567410]
environments=['S5', 'Z5']

[EXPERIMENT.PHASES.verificationBM]
repetitions = 1

[EXPERIMENT.PHASES.verificationBM.freestyle]
schedules = [ "../RepetiTouchFiles/S5/315s_pause.rpt", "../RepetiTouchFiles/Z5/315s_pause.rpt",]
durations = [ 320, 320,]
environments = [ "S5", "Z5",]

# ------------------------------------------------------------------------------------------------ #
#                                    Platform: Bilbo                                             #
# ------------------------------------------------------------------------------------------------ #
[ENVIRONMENTS.Bilbo.APPS]
src = {executable = "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver", zone = "bigLITTLE", type="standalone"}
snk = {executable = "ch.ethz.exot.thermalsc/.MeterService", zone = "bigLITTLE"}

[ENVIRONMENTS.Bilbo.src]
COMPONENT_NAME = "ch.ethz.exot.intentproxy/.IntentProxyService"
ACTION         = "ch.ethz.exot.intents.IntentProxy.action.BUNDLE_EXTRAS"

[ENVIRONMENTS.Bilbo.src.ei]
"intent.flags" = 20
"looptimes"    = 1
"replayspeed"  = 1

[ENVIRONMENTS.Bilbo.src.es]
"intent.component" = "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver"
"intent.action"    = "com.twofortyfouram.locale.intent.action.FIRE_SETTING"
"intent.extra.key" = "com.twofortyfouram.locale.intent.extra.BUNDLE"
"condition"        = "None"
"action"           = "Start Replay"

[ENVIRONMENTS.Bilbo.src.ez]
"appendingrecord"  = false
"hidepanel"        = true
"closeafteraction" = false
"silent"           = false        

[ENVIRONMENTS.Bilbo.snk]
logging.log_level      = "info"
host.log_header        = true
host.start_immediately = false

# ------------------------------------------------------------------------------------------------ #
#                                    Platform: Frodo                                               #
# ------------------------------------------------------------------------------------------------ #
[ENVIRONMENTS.Frodo.APPS]
src = {executable = "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver", zone = "bigLITTLE", type="standalone"}
snk = {executable = "ch.ethz.exot.thermalsc/.MeterService", zone = "bigLITTLE"}

[ENVIRONMENTS.Frodo.src]
COMPONENT_NAME = "ch.ethz.exot.intentproxy/.IntentProxyService"
ACTION         = "ch.ethz.exot.intents.IntentProxy.action.BUNDLE_EXTRAS"

[ENVIRONMENTS.Frodo.src.ei]
"intent.flags" = 20
"looptimes"    = 1
"replayspeed"  = 1

[ENVIRONMENTS.Frodo.src.es]
"intent.component" = "com.cygery.repetitouch.pro/com.cygery.repetitouch.pro.FireReceiver"
"intent.action"    = "com.twofortyfouram.locale.intent.action.FIRE_SETTING"
"intent.extra.key" = "com.twofortyfouram.locale.intent.extra.BUNDLE"
"condition"        = "None"
"action"           = "Start Replay"

[ENVIRONMENTS.Frodo.src.ez]
"appendingrecord"  = false
"hidepanel"        = true
"closeafteraction" = false
"silent"           = false        

[ENVIRONMENTS.Frodo.snk]
logging.log_level      = "info"
host.log_header        = true
host.start_immediately = false


[ANALYSES]
# ------------------------------------------------------------------------------------------------ #
#                                 Dragonboard Data Imitation Bilbo                                 #
# ------------------------------------------------------------------------------------------------ #
[ANALYSES.data_bilbo_feasibility]
type = "DataAugmentation"

[ANALYSES.data_bilbo_feasibility.DATASET]
env                       = 'Bilbo'
ambient                   = [-10,40]
dynamic_start             = [20,60]
thermal_throttling        = 100
batch_size_s              = 10800 # 3 hours 00 minutes 
num_train_batches         = 28   # 35 * 3 = 105h 00m in total
num_test_batches          =  7   # 35 * 3 = 105h 00m in total
min_len_profile_s         = 30 
train_phases              = ['bm']
test_phases               = ['bm']
verif_phases              = ['verificationBM']
duration_context_change_s = 4
resampling_period_s       = 0.040
augmentation_train        = true
augmentation_test         = true
augmentation_verif        = true
num_verif_batches         = 5

[ANALYSES.data_bilbo_feasibility.DATASET.matcher_data]
quantity   = "thermal"
method     = "sysfs"
values     = ["zone"]
dimensions = [2,3,4,5,6,9,10,11] # Bilbo CPUs only

[ANALYSES.data_bilbo_feasibility.DATASET.matcher_labels]
quantity   = "process"
method     = "android"
values     = ["ForegroundActivity"]
dimensions = [0]

[ANALYSES.data_bilbo_feasibility.DATASET.label_refactoring_rule]
[ANALYSES.data_bilbo_feasibility.DATASET.label_refactoring_rule."remove_unknown"]
train = true 
test  = true 
verif = true  
[ANALYSES.data_bilbo_feasibility.DATASET.label_refactoring_rule."extend"]
affected_labels    = [0,1,2,3,4,5,6,7,8,9,10]
extension_period_s = [0,4]
[ANALYSES.data_bilbo_feasibility.DATASET.label_refactoring_rule."replace"]
affected_labels         = [-1]
with                    = "before"
[ANALYSES.data_bilbo_feasibility.DATASET.label_refactoring_rule."smoothen"]
threshold_s = 1

[ANALYSES.data_bilbo_feasibility.DATASET.label_mapping]
"com.antutu.ABenchMark".int                = 0
"com.antutu.ABenchMark".str                = "VM"
"com.andromeda.androbench2".int            = 1
"com.andromeda.androbench2".str            = "BM"
"com.rovio.angrybirdsrio".int              = 2
"com.rovio.angrybirdsrio".str              = "GA"
"com.android.chrome".int                   = 3
"com.android.chrome".str                   = "WB"
"com.google.android.youtube".int           = 4
"com.google.android.youtube".str           = "VI"
"ch.ethz.exot.thermalsc:MeterService".int  = -1
"ch.ethz.exot.thermalsc:MeterService".str  = "N/A"
"org.eth.tik.meter".int                    = -1
"org.eth.tik.meter".str                    = "N/A"
"ch.ethz.karajan.thermalsc".int            = -1
"ch.ethz.karajan.thermalsc".str            = "N/A"
"~~~~~~~NOT FOUND~~~~~~~".int              = -1
"~~~~~~~NOT FOUND~~~~~~~".str              = "N/A"
"com.android.systemui.recentsactivity".int = -1
"com.android.systemui.recentsactivity".str = "N/A"
"com.cygery.repetitouch.pro".int           = -1
"com.cygery.repetitouch.pro".str           = "N/A"
"com.google.android.gms".int               = -1
"com.google.android.gms".str               = "N/A"

# ------------------------------------------------------------------------------------------------ #
#                                 Dragonboard Data Imitation Frodo                                 #
# ------------------------------------------------------------------------------------------------ #
[ANALYSES.data_frodo_feasibility]
type = "DataAugmentation"

[ANALYSES.data_frodo_feasibility.DATASET]
env                       = 'Frodo'
ambient                   = [-10,40]
dynamic_start             = [20,60]
thermal_throttling        = 100
batch_size_s              = 10800 # 3 hours 00 minutes 
num_train_batches         = 28   # 35 * 3 = 105h 00m in total
num_test_batches          =  7   # 35 * 3 = 105h 00m in total
min_len_profile_s         = 30 
train_phases              = ['bm']
test_phases               = ['bm']
verif_phases              = ['verificationBM']
duration_context_change_s = 4
resampling_period_s       = 0.040
augmentation_train        = true
augmentation_test         = true
augmentation_verif        = true
num_verif_batches         = 5

[ANALYSES.data_frodo_feasibility.DATASET.matcher_data]
quantity   = "thermal"
method     = "sysfs"
values     = ["zone"]
dimensions = [0]                 # Frodo CPUs only

[ANALYSES.data_frodo_feasibility.DATASET.matcher_labels]
quantity   = "process"
method     = "android"
values     = ["ForegroundActivity"]
dimensions = [0]

[ANALYSES.data_frodo_feasibility.DATASET.label_refactoring_rule]
[ANALYSES.data_frodo_feasibility.DATASET.label_refactoring_rule."remove_unknown"]
train = true 
test  = true 
verif = true  
[ANALYSES.data_frodo_feasibility.DATASET.label_refactoring_rule."extend"]
affected_labels    = [0,1,2,3,4,5,6,7,8,9,10]
extension_period_s = [0,4]
[ANALYSES.data_frodo_feasibility.DATASET.label_refactoring_rule."replace"]
affected_labels         = [-1]
with                    = "before"
[ANALYSES.data_frodo_feasibility.DATASET.label_refactoring_rule."smoothen"]
threshold_s = 1

[ANALYSES.data_frodo_feasibility.DATASET.label_mapping]
"com.antutu.ABenchMark".int                = 0
"com.antutu.ABenchMark".str                = "VM"
"com.andromeda.androbench2".int            = 1
"com.andromeda.androbench2".str            = "BM"
"com.rovio.angrybirdsrio".int              = 2
"com.rovio.angrybirdsrio".str              = "GA"
"com.android.chrome".int                   = 3
"com.android.chrome".str                   = "WB"
"com.google.android.youtube".int           = 4
"com.google.android.youtube".str           = "VI"
"ch.ethz.exot.thermalsc:MeterService".int  = -1
"ch.ethz.exot.thermalsc:MeterService".str  = "N/A"
"org.eth.tik.meter".int                    = -1
"org.eth.tik.meter".str                    = "N/A"
"ch.ethz.karajan.thermalsc".int            = -1
"ch.ethz.karajan.thermalsc".str            = "N/A"
"~~~~~~~NOT FOUND~~~~~~~".int              = -1
"~~~~~~~NOT FOUND~~~~~~~".str              = "N/A"
"com.android.systemui.recentsactivity".int = -1
"com.android.systemui.recentsactivity".str = "N/A"
"com.cygery.repetitouch.pro".int           = -1
"com.cygery.repetitouch.pro".str           = "N/A"
"com.google.android.gms".int               = -1
"com.google.android.gms".str               = "N/A"

# ------------------------------------------------------------------------------------------------ #
#                                   Analysis Feasibility Bilbo                                     #
# ------------------------------------------------------------------------------------------------ #
#[ANALYSES.proc_bilbo_feasibility]
#type = "AppDetection"
#[ANALYSES.proc_bilbo_feasibility.DATASET]
#load_from                = 'data_bilbo_feasibility'
#
#[ANALYSES.proc_bilbo_feasibility.TRAIN]
#n_epochs                 = 1500
#debug_step               = 10
#early_stopping_threshold = 20
#
#[ANALYSES.proc_bilbo_feasibility.MODEL]
#type          = 'LSTM'
#max_grad_norm = 5.0
#p_dropout     = 0.2
#num_layers    = 4
#num_hidden    = 128
#learning_rate = 0.001
#max_timesteps = 15000 # 15 minutes
#filtering_window_size = 75  # 3 seconds
##model_files   = path without .meta

[ANALYSES.proc_bilbo_feasibility_16875]
type = "AppDetection"
[ANALYSES.proc_bilbo_feasibility_16875.DATASET]
load_from                = 'data_bilbo_feasibility'

[ANALYSES.proc_bilbo_feasibility_16875.TRAIN]
n_epochs                 = 1500
debug_step               = 10
early_stopping_threshold = 60

[ANALYSES.proc_bilbo_feasibility_16875.MODEL]
type          = 'LSTM'
max_grad_norm = 5.0
p_dropout     = 0.2
num_layers    = 4
num_hidden    = 128
learning_rate = 0.001
max_timesteps = 16875
#max_timesteps = 33750
#max_timesteps = 67500
filtering_window_size = 0  # filtering disabled
#model_files   = path without .meta

[ANALYSES.proc_bilbo_feasibility_33750]
type = "AppDetection"
[ANALYSES.proc_bilbo_feasibility_33750.DATASET]
load_from                = 'data_bilbo_feasibility'

[ANALYSES.proc_bilbo_feasibility_33750.TRAIN]
n_epochs                 = 1500
debug_step               = 10
early_stopping_threshold = 60

[ANALYSES.proc_bilbo_feasibility_33750.MODEL]
type          = 'LSTM'
max_grad_norm = 5.0
p_dropout     = 0.2
num_layers    = 4
num_hidden    = 128
learning_rate = 0.001
#max_timesteps = 16875
max_timesteps = 33750
#max_timesteps = 67500
filtering_window_size = 0  # filtering disabled
#model_files   = path without .meta

[ANALYSES.proc_bilbo_feasibility_67500]
type = "AppDetection"
[ANALYSES.proc_bilbo_feasibility_67500.DATASET]
load_from                = 'data_bilbo_feasibility'

[ANALYSES.proc_bilbo_feasibility_67500.TRAIN]
n_epochs                 = 1500
debug_step               = 10
early_stopping_threshold = 60

[ANALYSES.proc_bilbo_feasibility_67500.MODEL]
type          = 'LSTM'
max_grad_norm = 5.0
p_dropout     = 0.2
num_layers    = 4
num_hidden    = 128
learning_rate = 0.001
#max_timesteps = 16875
#max_timesteps = 33750
max_timesteps = 67500
filtering_window_size = 0  # filtering disabled
#model_files   = path without .meta

# ------------------------------------------------------------------------------------------------ #
#                                   Analysis Feasibility Frodo                                     #
# ------------------------------------------------------------------------------------------------ #
[ANALYSES.proc_frodo_feasibility_16875]
type = "AppDetection"
[ANALYSES.proc_frodo_feasibility_16875.DATASET]
load_from                = 'data_frodo_feasibility'

[ANALYSES.proc_frodo_feasibility_16875.TRAIN]
n_epochs                 = 1500
debug_step               = 10
early_stopping_threshold = 60

[ANALYSES.proc_frodo_feasibility_16875.MODEL]
type          = 'LSTM'
max_grad_norm = 5.0
p_dropout     = 0.2
num_layers    = 4
num_hidden    = 128
learning_rate = 0.001
max_timesteps = 16875
#max_timesteps = 33750
#max_timesteps = 67500
filtering_window_size = 0  # filtering disabled
#model_files   = path without .meta

[ANALYSES.proc_frodo_feasibility_33750]
type = "AppDetection"
[ANALYSES.proc_frodo_feasibility_33750.DATASET]
load_from                = 'data_frodo_feasibility'

[ANALYSES.proc_frodo_feasibility_33750.TRAIN]
n_epochs                 = 1500
debug_step               = 10
early_stopping_threshold = 60

[ANALYSES.proc_frodo_feasibility_33750.MODEL]
type          = 'LSTM'
max_grad_norm = 5.0
p_dropout     = 0.2
num_layers    = 4
num_hidden    = 128
learning_rate = 0.001
#max_timesteps = 16875
max_timesteps = 33750
#max_timesteps = 67500
filtering_window_size = 0  # filtering disabled
#model_files   = path without .meta

[ANALYSES.proc_frodo_feasibility_67500]
type = "AppDetection"
[ANALYSES.proc_frodo_feasibility_67500.DATASET]
load_from                = 'data_frodo_feasibility'

[ANALYSES.proc_frodo_feasibility_67500.TRAIN]
n_epochs                 = 1500
debug_step               = 10
early_stopping_threshold = 60

[ANALYSES.proc_frodo_feasibility_67500.MODEL]
type          = 'LSTM'
max_grad_norm = 5.0
p_dropout     = 0.2
num_layers    = 4
num_hidden    = 128
learning_rate = 0.001
#max_timesteps = 16875
#max_timesteps = 33750
max_timesteps = 67500
filtering_window_size = 0  # filtering disabled
#model_files   = path without .meta

